# Generated by Django 5.2 on 2025-04-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='atendimento',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='atendimento_agil',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='mix_produtos',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='prazo_entrega',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='sugestao_melhoria',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='valores_produtos',
        ),
        migrations.AddField(
            model_name='feedback',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='recomendacao',
            field=models.IntegerField(default=1, help_text='Escala de 0 a 10 para NPS'),
            preserve_default=False,
        ),
    ]
